M48
; DRILL file {KiCad 8.0.2} date 2024-09-13T22:40:20+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-13T22:40:20+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X82.665Y-60.31
X87.515Y-60.31
T2
X82.365Y-57.28
X87.815Y-57.28
T3
X68.58Y-57.15
X68.58Y-113.03
X157.48Y-57.15
X157.48Y-113.03
M30
